apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/home
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
