deployment:
  #strategy: RollingUpdate
  # Resource limitations for the pod
  resources:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi

ngshare:
  hub_api_token: dbfbe0caddbe4f9dbe6ebdc27024d80b
  # Please change the line below with the namespace your Z2JH helm chart is installed under
  # You can omit this value if you're installing ngshare in the same namespace
  hub_api_url: http://proxy-api.entorn.svc.cluster.local:8001/hub/api
  admins:
    - orboan

pvc:
  # Amount of storage to allocate
  storage: 15Gi
  storageClassName: hostpath

